-- Oracle schema: He thong quan ly chuoi cua hang cafe

CREATE TABLE VAITRO (
    ma_vai_tro NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_vai_tro VARCHAR2
(50) NOT NULL UNIQUE
);

CREATE TABLE CHUCNANG (
    ma_chuc_nang NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_chuc_nang VARCHAR2
(50) NOT NULL UNIQUE
);

CREATE TABLE QUYEN (
    ma_quyen NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_chuc_nang NUMBER
(19) NOT NULL,
    hanh_dong VARCHAR2
(50) NOT NULL,
    ten_quyen VARCHAR2
(100) NOT NULL,
    CONSTRAINT fk_quyen_chucnang FOREIGN KEY
(ma_chuc_nang) REFERENCES CHUCNANG
(ma_chuc_nang),
    CONSTRAINT uq_quyen_chucnang_hanhdong UNIQUE
(ma_chuc_nang, hanh_dong),
    CONSTRAINT ck_quyen_hanh_dong CHECK
(
        hanh_dong IN
(
            'VIEW', 'CREATE', 'UPDATE', 'DELETE',
            'IMPORT', 'EXPORT', 'TRANSFER', 'ADJUST',
            'PAY', 'CANCEL', 'REFUND', 'MANAGE'
        )
    )
);

CREATE TABLE VAITRO_QUYEN
(
    ma_vai_tro NUMBER(19) NOT NULL,
    ma_quyen NUMBER(19) NOT NULL,
    CONSTRAINT pk_vaitro_quyen PRIMARY KEY (ma_vai_tro, ma_quyen),
    CONSTRAINT fk_vtq_vaitro FOREIGN KEY (ma_vai_tro) REFERENCES VAITRO(ma_vai_tro),
    CONSTRAINT fk_vtq_quyen FOREIGN KEY (ma_quyen) REFERENCES QUYEN(ma_quyen)
);

CREATE TABLE CHINHANH (
    ma_chi_nhanh NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_chi_nhanh VARCHAR2
(150) NOT NULL,
    dia_chi VARCHAR2
(255),
    so_dien_thoai VARCHAR2
(30),
    trang_thai VARCHAR2
(30) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT ck_chinhanh_trang_thai CHECK
(trang_thai IN
('ACTIVE', 'CLOSED', 'MAINTENANCE'))
);

CREATE TABLE NGUOIDUNG (
    ma_nguoi_dung NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_dang_nhap VARCHAR2
(80) NOT NULL UNIQUE,
    mat_khau VARCHAR2
(255) NOT NULL,
    email VARCHAR2
(150) NOT NULL UNIQUE,
    ma_vai_tro NUMBER
(19) NOT NULL,
    ma_chi_nhanh NUMBER
(19),
    trang_thai VARCHAR2
(30) DEFAULT 'ACTIVE' NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP,
    CONSTRAINT fk_nd_vaitro FOREIGN KEY
(ma_vai_tro) REFERENCES VAITRO
(ma_vai_tro),
    CONSTRAINT fk_nd_chinhanh FOREIGN KEY
(ma_chi_nhanh) REFERENCES CHINHANH
(ma_chi_nhanh),
    CONSTRAINT ck_nd_trang_thai CHECK
(trang_thai IN
('ACTIVE', 'INACTIVE', 'LOCKED'))
);

CREATE TABLE MAYPOS (
    ma_pos NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_chi_nhanh NUMBER
(19) NOT NULL,
    ma_thiet_bi VARCHAR2
(100) UNIQUE,
    trang_thai_thiet_bi VARCHAR2
(30) DEFAULT 'OFFLINE' NOT NULL,
    lan_dong_bo_cuoi TIMESTAMP,
    CONSTRAINT fk_pos_chinhanh FOREIGN KEY
(ma_chi_nhanh) REFERENCES CHINHANH
(ma_chi_nhanh),
    CONSTRAINT uq_pos_chinhanh UNIQUE
(ma_chi_nhanh),
    CONSTRAINT ck_pos_trang_thai CHECK
(trang_thai_thiet_bi IN
('ONLINE', 'OFFLINE', 'DISABLED'))
);

CREATE TABLE SANPHAM (
    ma_san_pham NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_san_pham VARCHAR2
(150) NOT NULL,
    hinh_anh VARCHAR2
(255),
    gia_ban_hien_tai NUMBER
(18,2),
    trang_thai VARCHAR2
(30) DEFAULT 'AVAILABLE' NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_sp_trang_thai CHECK
(trang_thai IN
('AVAILABLE', 'OUT_OF_STOCK', 'STOP_SELLING')),
    CONSTRAINT ck_sp_gia_ban CHECK
(gia_ban_hien_tai IS NULL OR gia_ban_hien_tai >= 0)
);

CREATE TABLE DONVITINH (
    ma_don_vi_tinh NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_don_vi_tinh VARCHAR2
(50) NOT NULL,
    ky_hieu VARCHAR2
(20) NOT NULL UNIQUE
);

CREATE TABLE NGUYENLIEU (
    ma_nguyen_lieu NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_nguyen_lieu VARCHAR2
(150) NOT NULL,
    ma_don_vi_tinh NUMBER
(19) NOT NULL,
    muc_ton_toi_thieu NUMBER
(18,3) DEFAULT 0 NOT NULL,
    trang_thai VARCHAR2
(30) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_nl_dvt FOREIGN KEY
(ma_don_vi_tinh) REFERENCES DONVITINH
(ma_don_vi_tinh),
    CONSTRAINT ck_nl_trang_thai CHECK
(trang_thai IN
('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_nl_muc_ton_min CHECK
(muc_ton_toi_thieu >= 0)
);

CREATE TABLE CONGTHUC_SANPHAM (
    ma_cong_thuc NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_san_pham NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    so_luong_can NUMBER
(18,3) NOT NULL,
    CONSTRAINT fk_ct_sp FOREIGN KEY
(ma_san_pham) REFERENCES SANPHAM
(ma_san_pham),
    CONSTRAINT fk_ct_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT uq_ct_sp_nl UNIQUE
(ma_san_pham, ma_nguyen_lieu),
    CONSTRAINT ck_ct_so_luong_can CHECK
(so_luong_can > 0)
);

CREATE TABLE KHO (
    ma_kho NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_kho VARCHAR2
(150) NOT NULL,
    loai_kho VARCHAR2
(30) NOT NULL,
    ma_chi_nhanh NUMBER
(19),
    trang_thai VARCHAR2
(30) DEFAULT 'ACTIVE' NOT NULL,

    CONSTRAINT fk_kho_chinhanh FOREIGN KEY
(ma_chi_nhanh) REFERENCES CHINHANH
(ma_chi_nhanh),
    CONSTRAINT ck_kho_loai CHECK
(loai_kho IN
('CENTRAL', 'BRANCH')),
    CONSTRAINT ck_kho_trang_thai CHECK
(trang_thai IN
('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_kho_chinhanh_theo_loai CHECK
(
        (loai_kho = 'CENTRAL' AND ma_chi_nhanh IS NULL)
        OR
(loai_kho = 'BRANCH' AND ma_chi_nhanh IS NOT NULL)
    ),
    CONSTRAINT uq_kho_chinhanh UNIQUE
(ma_chi_nhanh)
);

CREATE TABLE TONKHO (
    ma_ton_kho NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    so_luong_ton NUMBER
(18,3) DEFAULT 0 NOT NULL,
    lan_cap_nhat_cuoi TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_tk_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_tk_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT uq_tk_kho_nl UNIQUE
(ma_kho, ma_nguyen_lieu),
    CONSTRAINT ck_tk_so_luong_ton CHECK
(so_luong_ton >= 0)
);

CREATE TABLE NHACUNGCAP (
    ma_nha_cung_cap NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ten_nha_cung_cap VARCHAR2
(150) NOT NULL,
    so_dien_thoai VARCHAR2
(30),
    email VARCHAR2
(100),
    dia_chi VARCHAR2
(255)
);

CREATE TABLE PHIEUNHAP (
    ma_phieu_nhap NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ma_nha_cung_cap NUMBER
(19) NOT NULL,
    ngay_nhap TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    tong_tien NUMBER
(18,2) DEFAULT 0 NOT NULL,
    nguoi_tao NUMBER
(19),
    ghi_chu VARCHAR2
(255),

    CONSTRAINT fk_pn_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_pn_ncc FOREIGN KEY
(ma_nha_cung_cap) REFERENCES NHACUNGCAP
(ma_nha_cung_cap),
    CONSTRAINT fk_pn_nd FOREIGN KEY
(nguoi_tao) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_pn_tong_tien CHECK
(tong_tien >= 0)
);

CREATE TABLE CHITIETPHIEUNHAP (
    ma_ct_phieu_nhap NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_phieu_nhap NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    so_luong_nhap NUMBER
(18,3) NOT NULL,
    don_gia_nhap NUMBER
(18,2) DEFAULT 0 NOT NULL,
    so_lo VARCHAR2
(80),
    han_su_dung DATE,
    CONSTRAINT fk_ctpn_pn FOREIGN KEY
(ma_phieu_nhap) REFERENCES PHIEUNHAP
(ma_phieu_nhap),
    CONSTRAINT fk_ctpn_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT ck_ctpn_so_luong CHECK
(so_luong_nhap > 0),
    CONSTRAINT ck_ctpn_don_gia CHECK
(don_gia_nhap >= 0)
);

CREATE TABLE LOHANG_NGUYENLIEU (
    ma_lo_hang NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_ct_phieu_nhap NUMBER
(19),
    so_luong_con_lai NUMBER
(18,3) DEFAULT 0 NOT NULL,
    trang_thai VARCHAR2
(30) DEFAULT 'ACTIVE' NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    han_su_dung DATE,
    CONSTRAINT fk_lh_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_lh_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_lh_ctpn FOREIGN KEY
(ma_ct_phieu_nhap) REFERENCES CHITIETPHIEUNHAP
(ma_ct_phieu_nhap),
    CONSTRAINT ck_lh_trang_thai CHECK
(trang_thai IN
('ACTIVE', 'EXPIRED', 'USED_UP')),
    CONSTRAINT ck_lh_so_luong CHECK
(so_luong_con_lai >= 0)
);

CREATE TABLE PHIEUXUAT (
    ma_phieu_xuat NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ngay_xuat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    loai_xuat VARCHAR2
(50) NOT NULL,
    tong_gia_tri_xuat NUMBER
(18,2) DEFAULT 0 NOT NULL,
    nguoi_tao NUMBER
(19),
    trang_thai VARCHAR2
(30) DEFAULT 'DRAFT' NOT NULL,
    ghi_chu VARCHAR2
(255),
    CONSTRAINT fk_px_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_px_nd FOREIGN KEY
(nguoi_tao) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_px_loai_xuat CHECK
(loai_xuat IN
('INTERNAL_USE', 'RETURN_SUPPLIER', 'TRAINING', 'OTHER')),
    CONSTRAINT ck_px_trang_thai CHECK
(trang_thai IN
('DRAFT', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_px_tong_gia_tri CHECK
(tong_gia_tri_xuat >= 0)
);

CREATE TABLE CHITIETPHIEUXUAT (
    ma_ct_phieu_xuat NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_phieu_xuat NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_lo_hang NUMBER
(19),
    so_luong_xuat NUMBER
(18,3) NOT NULL,
    don_gia_xuat NUMBER
(18,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_ctpx_px FOREIGN KEY
(ma_phieu_xuat) REFERENCES PHIEUXUAT
(ma_phieu_xuat),
    CONSTRAINT fk_ctpx_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_ctpx_lh FOREIGN KEY
(ma_lo_hang) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT ck_ctpx_so_luong CHECK
(so_luong_xuat > 0),
    CONSTRAINT ck_ctpx_don_gia CHECK
(don_gia_xuat >= 0)
);

CREATE TABLE PHIEUDIEUCHUYEN (
    ma_phieu_dieu_chuyen NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho_nguon NUMBER
(19) NOT NULL,
    ma_kho_dich NUMBER
(19) NOT NULL,
    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trang_thai VARCHAR2
(30) DEFAULT 'PENDING' NOT NULL,
    nguoi_tao NUMBER
(19),
    ghi_chu VARCHAR2
(255),
    CONSTRAINT fk_pdc_kho_nguon FOREIGN KEY
(ma_kho_nguon) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_pdc_kho_dich FOREIGN KEY
(ma_kho_dich) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_pdc_nd FOREIGN KEY
(nguoi_tao) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_pdc_trang_thai CHECK
(trang_thai IN
('PENDING', 'COMPLETED', 'CANCELLED')),
    CONSTRAINT ck_pdc_kho_khac_nhau CHECK
(ma_kho_nguon <> ma_kho_dich)
);

CREATE TABLE CHITIETPHIEUDIEUCHUYEN (
    ma_ct_phieu_dieu_chuyen NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_phieu_dieu_chuyen NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_lo_hang_nguon NUMBER
(19),
    ma_lo_hang_dich NUMBER
(19),
    so_luong_dieu_chuyen NUMBER
(18,3) NOT NULL,
    CONSTRAINT fk_ctpdc_pdc FOREIGN KEY
(ma_phieu_dieu_chuyen) REFERENCES PHIEUDIEUCHUYEN
(ma_phieu_dieu_chuyen),
    CONSTRAINT fk_ctpdc_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_ctpdc_lh_nguon FOREIGN KEY
(ma_lo_hang_nguon) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT fk_ctpdc_lh_dich FOREIGN KEY
(ma_lo_hang_dich) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT ck_ctpdc_so_luong CHECK
(so_luong_dieu_chuyen > 0)
);

CREATE TABLE PHIEUKIEMKHO (
    ma_phieu_kiem_kho NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ngay_kiem_kho TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nguoi_kiem NUMBER
(19),
    trang_thai VARCHAR2
(30) DEFAULT 'DRAFT' NOT NULL,
    ghi_chu VARCHAR2
(255),
    CONSTRAINT fk_pkk_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_pkk_nd FOREIGN KEY
(nguoi_kiem) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_pkk_trang_thai CHECK
(trang_thai IN
('DRAFT', 'COMPLETED', 'CANCELLED'))
);

CREATE TABLE CHITIETPHIEUKIEMKHO (
    ma_ct_phieu_kiem_kho NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_phieu_kiem_kho NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_lo_hang NUMBER
(19),
    so_luong_he_thong NUMBER
(18,3) DEFAULT 0 NOT NULL,
    so_luong_thuc_te NUMBER
(18,3) DEFAULT 0 NOT NULL,
    so_luong_chenh_lech NUMBER
(18,3) DEFAULT 0 NOT NULL,
    ty_le_chenh_lech NUMBER
(9,4),
    ly_do_chenh_lech VARCHAR2
(255),
    huong_xu_ly VARCHAR2
(50) DEFAULT 'NO_ACTION' NOT NULL,
    CONSTRAINT fk_ctpkk_pkk FOREIGN KEY
(ma_phieu_kiem_kho) REFERENCES PHIEUKIEMKHO
(ma_phieu_kiem_kho),
    CONSTRAINT fk_ctpkk_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_ctpkk_lh FOREIGN KEY
(ma_lo_hang) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT ck_ctpkk_so_luong_ht CHECK
(so_luong_he_thong >= 0),
    CONSTRAINT ck_ctpkk_so_luong_tt CHECK
(so_luong_thuc_te >= 0),
    CONSTRAINT ck_ctpkk_huong_xu_ly CHECK
(huong_xu_ly IN
('ADJUST_STOCK', 'CREATE_WASTAGE', 'NO_ACTION'))
);

CREATE TABLE PHIEUHAOHUT (
    ma_phieu_hao_hut NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_lo_hang NUMBER
(19),
    so_luong_hao_hut NUMBER
(18,3) NOT NULL,
    loai_hao_hut VARCHAR2
(50) NOT NULL,
    ngay_hao_hut TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ghi_chu VARCHAR2
(255),
    nguoi_bao_cao NUMBER
(19),
    CONSTRAINT fk_phh_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_phh_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_phh_lh FOREIGN KEY
(ma_lo_hang) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT fk_phh_nd FOREIGN KEY
(nguoi_bao_cao) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_phh_so_luong CHECK
(so_luong_hao_hut > 0),
    CONSTRAINT ck_phh_loai CHECK
(loai_hao_hut IN
('EXPIRED', 'DAMAGED', 'LOST', 'SPILL'))
);

CREATE TABLE HOADON (
    ma_hoa_don NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_chi_nhanh NUMBER
(19) NOT NULL,
    ma_pos NUMBER
(19) NOT NULL,
    ma_nguoi_dung NUMBER
(19) NOT NULL,

    thoi_gian_tao_hoa_don TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trang_thai_hoa_don VARCHAR2
(30) DEFAULT 'PENDING' NOT NULL,

    tong_thanh_toan NUMBER
(18,2) DEFAULT 0 NOT NULL,

    phuong_thuc_thanh_toan VARCHAR2
(50),
    thoi_gian_thanh_toan TIMESTAMP,
    trang_thai_thanh_toan VARCHAR2
(30) DEFAULT 'PENDING' NOT NULL,

    CONSTRAINT fk_hd_chinhanh FOREIGN KEY
(ma_chi_nhanh) REFERENCES CHINHANH
(ma_chi_nhanh),
    CONSTRAINT fk_hd_pos FOREIGN KEY
(ma_pos) REFERENCES MAYPOS
(ma_pos),
    CONSTRAINT fk_hd_nd FOREIGN KEY
(ma_nguoi_dung) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_hd_trang_thai_hoa_don CHECK
(trang_thai_hoa_don IN
('PENDING', 'PAID', 'COMPLETED', 'CANCELLED', 'REFUNDED')),
    CONSTRAINT ck_hd_phuong_thuc_tt CHECK
(phuong_thuc_thanh_toan IS NULL OR phuong_thuc_thanh_toan IN
('CASH', 'BANK_TRANSFER', 'EWALLET')),
    CONSTRAINT ck_hd_trang_thai_tt CHECK
(trang_thai_thanh_toan IN
('SUCCESS', 'FAILED', 'PENDING')),
    CONSTRAINT ck_hd_tong_thanh_toan CHECK
(tong_thanh_toan >= 0)
);

CREATE TABLE CHITIETHOADON (
    ma_ct_hoa_don NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_hoa_don NUMBER
(19) NOT NULL,
    ma_san_pham NUMBER
(19) NOT NULL,
    so_luong NUMBER
(10) NOT NULL,
    don_gia_ban NUMBER
(18,2) DEFAULT 0 NOT NULL,
    thanh_tien_dong NUMBER
(18,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_cthd_hd FOREIGN KEY
(ma_hoa_don) REFERENCES HOADON
(ma_hoa_don),
    CONSTRAINT fk_cthd_sp FOREIGN KEY
(ma_san_pham) REFERENCES SANPHAM
(ma_san_pham),
    CONSTRAINT ck_cthd_so_luong CHECK
(so_luong > 0),
    CONSTRAINT ck_cthd_don_gia CHECK
(don_gia_ban >= 0),
    CONSTRAINT ck_cthd_thanh_tien CHECK
(thanh_tien_dong >= 0)
);

CREATE TABLE THANHTOAN_PAYOS (
    ma_thanh_toan NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,

    ma_hoa_don NUMBER(19) NOT NULL,

    -- orderCode gửi sang payOS, nên unique để tránh trùng đơn
    order_code NUMBER(19) NOT NULL,

    payment_link_id VARCHAR2(100),
    checkout_url VARCHAR2(1000),
    qr_code CLOB,

    so_tien NUMBER(18,2) NOT NULL,
    mo_ta VARCHAR2(50),

    trang_thai VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,

    -- dữ liệu payOS/webhook trả về để debug
    reference_code VARCHAR2(100),
    raw_webhook CLOB,

    ngay_tao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ngay_cap_nhat TIMESTAMP,
    ngay_thanh_toan TIMESTAMP,

    CONSTRAINT fk_ttpayos_hd FOREIGN KEY (ma_hoa_don)
        REFERENCES HOADON(ma_hoa_don),

    CONSTRAINT uq_ttpayos_order_code UNIQUE (order_code),
    
    CONSTRAINT uq_ttpayos_hoa_don UNIQUE (ma_hoa_don),

    CONSTRAINT ck_ttpayos_status CHECK (
        trang_thai IN ('PENDING', 'PAID', 'CANCELLED', 'FAILED')
    ),

    CONSTRAINT ck_ttpayos_amount CHECK (so_tien > 0)
);

CREATE TABLE BANHANG_TRUKHO (
    ma_ban_hang_tru_kho NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_hoa_don NUMBER
(19) NOT NULL,
    ma_ct_hoa_don NUMBER
(19) NOT NULL,
    ma_kho NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_lo_hang NUMBER
(19),
    so_luong_nguyen_lieu_moi_sp NUMBER
(18,3) NOT NULL,
    tong_so_luong_tru NUMBER
(18,3) NOT NULL,
    thoi_gian_tru_kho TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    trang_thai VARCHAR2
(30) DEFAULT 'DEDUCTED' NOT NULL,
    CONSTRAINT fk_bhtk_hd FOREIGN KEY
(ma_hoa_don) REFERENCES HOADON
(ma_hoa_don),
    CONSTRAINT fk_bhtk_cthd FOREIGN KEY
(ma_ct_hoa_don) REFERENCES CHITIETHOADON
(ma_ct_hoa_don),
    CONSTRAINT fk_bhtk_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_bhtk_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_bhtk_lh FOREIGN KEY
(ma_lo_hang) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT ck_bhtk_trang_thai CHECK
(trang_thai IN
('DEDUCTED', 'REVERSED')),
    CONSTRAINT ck_bhtk_sl_moi_sp CHECK
(so_luong_nguyen_lieu_moi_sp > 0),
    CONSTRAINT ck_bhtk_tong_sl_tru CHECK
(tong_so_luong_tru > 0)
);

CREATE TABLE NHATKY_KHO (
    ma_nhat_ky_kho NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
    ma_kho NUMBER
(19) NOT NULL,
    ma_nguyen_lieu NUMBER
(19) NOT NULL,
    ma_lo_hang NUMBER
(19),
    loai_giao_dich VARCHAR2
(50) NOT NULL,
    ten_chung_tu VARCHAR2
(80),
    ma_chung_tu NUMBER
(19),
    so_luong_thay_doi NUMBER
(18,3) NOT NULL,
    so_luong_truoc NUMBER
(18,3) DEFAULT 0 NOT NULL,
    so_luong_sau NUMBER
(18,3) DEFAULT 0 NOT NULL,
    thoi_gian TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    nguoi_thao_tac NUMBER
(19),
    CONSTRAINT fk_nkk_kho FOREIGN KEY
(ma_kho) REFERENCES KHO
(ma_kho),
    CONSTRAINT fk_nkk_nl FOREIGN KEY
(ma_nguyen_lieu) REFERENCES NGUYENLIEU
(ma_nguyen_lieu),
    CONSTRAINT fk_nkk_lh FOREIGN KEY
(ma_lo_hang) REFERENCES LOHANG_NGUYENLIEU
(ma_lo_hang),
    CONSTRAINT fk_nkk_nd FOREIGN KEY
(nguoi_thao_tac) REFERENCES NGUOIDUNG
(ma_nguoi_dung),
    CONSTRAINT ck_nkk_loai_giao_dich CHECK
(
        loai_giao_dich IN
(
            'IMPORT', 'EXPORT',
            'TRANSFER_IN', 'TRANSFER_OUT',
            'WASTAGE',
            'SALE_DEDUCT', 'SALE_REVERSE',
            'STOCKTAKE_ADJUST'
        )
    ),
    CONSTRAINT ck_nkk_ton_truoc CHECK
(so_luong_truoc >= 0),
    CONSTRAINT ck_nkk_ton_sau CHECK
(so_luong_sau >= 0)
);

-------------------------------------------------------------------------------
-- TRIGGER / FUNCTION / PROCEDURE
-- Ghi chú chung:
-- 1. Các cột kiểu ngay_tao, ngay_nhap, ngay_xuat, thoi_gian...
--    đã có DEFAULT CURRENT_TIMESTAMP, nên không cần trigger update.
--
-- 2. Trigger chỉ nên dùng cho:
--    - metadata cập nhật cuối
--    - tính toán đơn giản trên cùng dòng
--    - kiểm tra dữ liệu tham chiếu
--
-- 3. Không dùng trigger để tự nhập/xuất/trừ kho/ghi NHATKY_KHO,
--    vì các nghiệp vụ này backend service đang xử lý trong transaction.
--    Nếu trigger cũng làm thì dễ bị cộng/trừ tồn kho 2 lần.
-------------------------------------------------------------------------------


-------------------------------------------------------------------------------
-- 1. TRIGGER ĐÃ CÓ: tự cập nhật TONKHO.lan_cap_nhat_cuoi
-- Mục đích:
-- - TONKHO.lan_cap_nhat_cuoi là thời điểm dòng tồn kho được cập nhật gần nhất.
-- - DEFAULT CURRENT_TIMESTAMP chỉ chạy khi INSERT.
-- - Trigger này chạy khi UPDATE so_luong_ton.
--
-- Ảnh hưởng backend:
-- - Ít ảnh hưởng.
-- - Backend có set lan_cap_nhat_cuoi hay không cũng được, DB sẽ set lại.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_tonkho_update_time
BEFORE UPDATE OF so_luong_ton ON TONKHO
FOR EACH ROW
BEGIN
    :NEW.lan_cap_nhat_cuoi := CURRENT_TIMESTAMP;
END;
/


-------------------------------------------------------------------------------
-- 2. TRIGGER ĐÃ CÓ: tự cập nhật trạng thái lô hàng
-- Mục đích:
-- - Nếu số lượng còn lại <= 0 thì lô chuyển sang USED_UP.
-- - Nếu lô quá hạn thì chuyển sang EXPIRED.
-- - Nếu còn hàng và chưa hết hạn thì ACTIVE.
--
-- Lưu ý:
-- - Trigger chỉ chạy khi INSERT hoặc UPDATE lô.
-- - Nếu một lô qua hạn do thời gian trôi qua nhưng không có update nào,
--   trigger sẽ không tự chạy. Vì vậy cần procedure prc_cap_nhat_lo_het_han.
--
-- Ảnh hưởng backend:
-- - Ít ảnh hưởng.
-- - Nếu backend cố tình set trạng thái khác với logic này, trigger sẽ ghi đè.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_lohang_update_status
BEFORE INSERT OR UPDATE OF so_luong_con_lai, han_su_dung ON LOHANG_NGUYENLIEU
FOR EACH ROW
BEGIN
    IF :NEW.so_luong_con_lai <= 0 THEN
        :NEW.trang_thai := 'USED_UP';
    ELSIF :NEW.han_su_dung IS NOT NULL
          AND :NEW.han_su_dung < TRUNC(SYSDATE) THEN
        :NEW.trang_thai := 'EXPIRED';
    ELSE
        :NEW.trang_thai := 'ACTIVE';
    END IF;
END;
/


-------------------------------------------------------------------------------
-- 3. TRIGGER THÊM MỚI: tự cập nhật NGUOIDUNG.ngay_cap_nhat
-- Mục đích:
-- - NGUOIDUNG.ngay_tao đã có DEFAULT CURRENT_TIMESTAMP cho lúc tạo mới.
-- - ngay_cap_nhat dùng để biết tài khoản được sửa lần cuối khi nào.
--
-- Ảnh hưởng backend:
-- - Ít ảnh hưởng.
-- - Nếu backend update user, DB tự set ngay_cap_nhat.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_nguoidung_update_time
BEFORE UPDATE ON NGUOIDUNG
FOR EACH ROW
BEGIN
    :NEW.ngay_cap_nhat := CURRENT_TIMESTAMP;
END;
/


-------------------------------------------------------------------------------
-- 4. TRIGGER THÊM MỚI: tự tính thành tiền dòng hóa đơn
-- Mục đích:
-- - CHITIETHOADON.thanh_tien_dong = so_luong * don_gia_ban.
-- - Giúp tránh sai lệch khi backend quên tính hoặc tính sai dòng tiền.
--
-- Ảnh hưởng backend:
-- - Có ảnh hưởng nhẹ.
-- - Backend không cần tự tính thanh_tien_dong nữa.
-- - Nếu backend gửi thanh_tien_dong khác công thức, DB sẽ ghi đè.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_cthd_calc_thanh_tien
BEFORE INSERT OR UPDATE OF so_luong, don_gia_ban ON CHITIETHOADON
FOR EACH ROW
BEGIN
    :NEW.thanh_tien_dong := :NEW.so_luong * :NEW.don_gia_ban;
END;
/


-------------------------------------------------------------------------------
-- 5. TRIGGER THÊM MỚI: tự set thời gian thanh toán hóa đơn
-- Mục đích:
-- - Khi trang_thai_thanh_toan chuyển thành SUCCESS,
--   nếu thoi_gian_thanh_toan đang NULL thì tự set CURRENT_TIMESTAMP.
-- - Nếu hóa đơn đang PENDING thì chuyển sang PAID.
--
-- Ảnh hưởng backend:
-- - Có ảnh hưởng nhẹ.
-- - Backend cần biết: khi update thanh toán SUCCESS,
--   DB có thể tự đổi trang_thai_hoa_don thành PAID.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_hoadon_payment_time
BEFORE INSERT OR UPDATE OF trang_thai_thanh_toan ON HOADON
FOR EACH ROW
BEGIN
    IF :NEW.trang_thai_thanh_toan = 'SUCCESS'
       AND :NEW.thoi_gian_thanh_toan IS NULL THEN
        :NEW.thoi_gian_thanh_toan := CURRENT_TIMESTAMP;
    END IF;

    IF :NEW.trang_thai_thanh_toan = 'SUCCESS'
       AND :NEW.trang_thai_hoa_don = 'PENDING' THEN
        :NEW.trang_thai_hoa_don := 'PAID';
    END IF;
END;
/


-------------------------------------------------------------------------------
-- 6. TRIGGER THÊM MỚI: tự tính chênh lệch kiểm kho
-- Mục đích:
-- - so_luong_chenh_lech = so_luong_thuc_te - so_luong_he_thong.
-- - ty_le_chenh_lech = chênh lệch / số lượng hệ thống.
--
-- Ảnh hưởng backend:
-- - Có ảnh hưởng nhẹ.
-- - Backend chỉ cần gửi so_luong_he_thong và so_luong_thuc_te.
-- - Nếu backend gửi sẵn so_luong_chenh_lech, DB vẫn tính lại.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_ctpkk_calc_chenh_lech
BEFORE INSERT OR UPDATE OF so_luong_he_thong, so_luong_thuc_te ON CHITIETPHIEUKIEMKHO
FOR EACH ROW
BEGIN
    :NEW.so_luong_chenh_lech := :NEW.so_luong_thuc_te - :NEW.so_luong_he_thong;

    IF :NEW.so_luong_he_thong > 0 THEN
        :NEW.ty_le_chenh_lech :=
            ROUND(:NEW.so_luong_chenh_lech / :NEW.so_luong_he_thong, 4);
    ELSE
        :NEW.ty_le_chenh_lech := NULL;
    END IF;
END;
/


-------------------------------------------------------------------------------
-- 7. TRIGGER THÊM MỚI - NÂNG CAO: kiểm tra lô xuất đúng nguyên liệu
-- Mục đích:
-- - CHITIETPHIEUXUAT có ma_nguyen_lieu và ma_lo_hang.
-- - Trigger chặn trường hợp backend gửi lô của nguyên liệu A
--   nhưng dòng xuất lại ghi nguyên liệu B.
--
-- Ảnh hưởng backend:
-- - Có thể làm API xuất kho fail nếu backend gửi sai ma_lo_hang.
-- - Đây là fail tốt vì bảo vệ dữ liệu.
-- - Nếu backend xuất kho chưa ổn, có thể tạm comment trigger này.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_ctpx_validate_lot_ingredient
BEFORE INSERT OR UPDATE OF ma_nguyen_lieu, ma_lo_hang ON CHITIETPHIEUXUAT
FOR EACH ROW
DECLARE
    v_ma_nguyen_lieu LOHANG_NGUYENLIEU.ma_nguyen_lieu%TYPE;
BEGIN
    IF :NEW.ma_lo_hang IS NOT NULL THEN
        SELECT ma_nguyen_lieu
        INTO v_ma_nguyen_lieu
        FROM LOHANG_NGUYENLIEU
        WHERE ma_lo_hang = :NEW.ma_lo_hang;

        IF v_ma_nguyen_lieu <> :NEW.ma_nguyen_lieu THEN
            RAISE_APPLICATION_ERROR(
                -20001,
                'Lo hang khong thuoc dung nguyen lieu cua dong xuat'
            );
        END IF;
    END IF;
END;
/


-------------------------------------------------------------------------------
-- 8. TRIGGER THÊM MỚI - NÂNG CAO: kiểm tra lô hao hụt đúng kho/nguyên liệu
-- Mục đích:
-- - PHIEUHAOHUT có ma_kho, ma_nguyen_lieu, ma_lo_hang.
-- - Trigger chặn trường hợp báo hao hụt một lô không thuộc kho/nguyên liệu đó.
--
-- Ảnh hưởng backend:
-- - Có thể làm API hao hụt fail nếu backend gửi sai lô.
-- - Nên thêm khi chức năng hao hụt đã gửi đúng ma_lo_hang.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_phh_validate_lot
BEFORE INSERT OR UPDATE OF ma_kho, ma_nguyen_lieu, ma_lo_hang ON PHIEUHAOHUT
FOR EACH ROW
DECLARE
    v_ma_kho LOHANG_NGUYENLIEU.ma_kho%TYPE;
    v_ma_nguyen_lieu LOHANG_NGUYENLIEU.ma_nguyen_lieu%TYPE;
BEGIN
    IF :NEW.ma_lo_hang IS NOT NULL THEN
        SELECT ma_kho, ma_nguyen_lieu
        INTO v_ma_kho, v_ma_nguyen_lieu
        FROM LOHANG_NGUYENLIEU
        WHERE ma_lo_hang = :NEW.ma_lo_hang;

        IF v_ma_kho <> :NEW.ma_kho OR v_ma_nguyen_lieu <> :NEW.ma_nguyen_lieu THEN
            RAISE_APPLICATION_ERROR(
                -20002,
                'Lo hang hao hut khong thuoc dung kho hoac nguyen lieu'
            );
        END IF;
    END IF;
END;
/


-------------------------------------------------------------------------------
-- 9. TRIGGER THÊM MỚI - NÂNG CAO: kiểm tra lô bán hàng trừ kho
-- Mục đích:
-- - BANHANG_TRUKHO lưu log POS trừ kho.
-- - Nếu có ma_lo_hang thì lô phải thuộc đúng kho và nguyên liệu.
--
-- Ảnh hưởng backend:
-- - Có thể làm API POS/trừ kho fail nếu backend gửi sai lô.
-- - Nên thêm khi chức năng POS/trừ kho đã ổn.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_bhtk_validate_lot
BEFORE INSERT OR UPDATE OF ma_kho, ma_nguyen_lieu, ma_lo_hang ON BANHANG_TRUKHO
FOR EACH ROW
DECLARE
    v_ma_kho LOHANG_NGUYENLIEU.ma_kho%TYPE;
    v_ma_nguyen_lieu LOHANG_NGUYENLIEU.ma_nguyen_lieu%TYPE;
BEGIN
    IF :NEW.ma_lo_hang IS NOT NULL THEN
        SELECT ma_kho, ma_nguyen_lieu
        INTO v_ma_kho, v_ma_nguyen_lieu
        FROM LOHANG_NGUYENLIEU
        WHERE ma_lo_hang = :NEW.ma_lo_hang;

        IF v_ma_kho <> :NEW.ma_kho OR v_ma_nguyen_lieu <> :NEW.ma_nguyen_lieu THEN
            RAISE_APPLICATION_ERROR(
                -20003,
                'Lo hang tru kho POS khong thuoc dung kho hoac nguyen lieu'
            );
        END IF;
    END IF;
END;
/


-------------------------------------------------------------------------------
-- 10. TRIGGER THÊM MỚI - NÂNG CAO: kiểm tra lô điều chuyển đúng nguyên liệu
-- Mục đích:
-- - CHITIETPHIEUDIEUCHUYEN có ma_nguyen_lieu, ma_lo_hang_nguon, ma_lo_hang_dich.
-- - Nếu có lô nguồn hoặc lô đích thì phải cùng nguyên liệu với dòng điều chuyển.
--
-- Ảnh hưởng backend:
-- - Có thể làm API điều chuyển fail nếu backend gán sai lô.
-- - Nếu backend tạo dòng điều chuyển trước rồi cập nhật lô đích sau, trigger vẫn cho phép
--   vì ma_lo_hang_dich có thể NULL.
-------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_ctpdc_validate_lots
BEFORE INSERT OR UPDATE OF ma_nguyen_lieu, ma_lo_hang_nguon, ma_lo_hang_dich ON CHITIETPHIEUDIEUCHUYEN
FOR EACH ROW
DECLARE
    v_ma_nguyen_lieu LOHANG_NGUYENLIEU.ma_nguyen_lieu%TYPE;
BEGIN
    IF :NEW.ma_lo_hang_nguon IS NOT NULL THEN
        SELECT ma_nguyen_lieu
        INTO v_ma_nguyen_lieu
        FROM LOHANG_NGUYENLIEU
        WHERE ma_lo_hang = :NEW.ma_lo_hang_nguon;

        IF v_ma_nguyen_lieu <> :NEW.ma_nguyen_lieu THEN
            RAISE_APPLICATION_ERROR(
                -20004,
                'Lo hang nguon khong thuoc dung nguyen lieu dieu chuyen'
            );
        END IF;
    END IF;

    IF :NEW.ma_lo_hang_dich IS NOT NULL THEN
        SELECT ma_nguyen_lieu
        INTO v_ma_nguyen_lieu
        FROM LOHANG_NGUYENLIEU
        WHERE ma_lo_hang = :NEW.ma_lo_hang_dich;

        IF v_ma_nguyen_lieu <> :NEW.ma_nguyen_lieu THEN
            RAISE_APPLICATION_ERROR(
                -20005,
                'Lo hang dich khong thuoc dung nguyen lieu dieu chuyen'
            );
        END IF;
    END IF;
END;
/


CREATE OR REPLACE TRIGGER trg_ttpayos_update_time
BEFORE UPDATE ON THANHTOAN_PAYOS
FOR EACH ROW
BEGIN
    :NEW.ngay_cap_nhat := CURRENT_TIMESTAMP;

    IF :NEW.trang_thai = 'PAID'
       AND :NEW.ngay_thanh_toan IS NULL THEN
        :NEW.ngay_thanh_toan := CURRENT_TIMESTAMP;
    END IF;
END;
/

-------------------------------------------------------------------------------
-- 11. PROCEDURE ĐÃ CÓ: rà soát lô hết hạn/hết hàng
-- Mục đích:
-- - Trigger trạng thái lô chỉ chạy khi insert/update.
-- - Procedure này dùng để quét định kỳ hoặc chạy khi demo.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng nếu chỉ chạy thủ công/bảo trì.
-- - Có COMMIT nên không nên gọi giữa một transaction nghiệp vụ backend.
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_cap_nhat_lo_het_han
AS
BEGIN
    UPDATE LOHANG_NGUYENLIEU
    SET trang_thai = 'EXPIRED'
    WHERE so_luong_con_lai > 0
      AND han_su_dung IS NOT NULL
      AND han_su_dung < TRUNC(SYSDATE)
      AND trang_thai <> 'EXPIRED';

    UPDATE LOHANG_NGUYENLIEU
    SET trang_thai = 'USED_UP'
    WHERE so_luong_con_lai = 0
      AND trang_thai <> 'USED_UP';

    COMMIT;
END;
/


-------------------------------------------------------------------------------
-- 12. FUNCTION ĐÃ CÓ: tính tồn thực tế từ lô hàng
-- Mục đích:
-- - LOHANG_NGUYENLIEU là source of truth theo lô.
-- - TONKHO là bảng tổng hợp để truy vấn nhanh.
-- - Function này giúp đối soát TONKHO với tổng lô thật.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng. Chỉ đọc dữ liệu.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_ton_tu_lo (
    p_ma_kho IN NUMBER,
    p_ma_nguyen_lieu IN NUMBER
) RETURN NUMBER
AS
    v_ton NUMBER(18,3);
BEGIN
    SELECT NVL(SUM(so_luong_con_lai), 0)
    INTO v_ton
    FROM LOHANG_NGUYENLIEU
    WHERE ma_kho = p_ma_kho
      AND ma_nguyen_lieu = p_ma_nguyen_lieu
      AND trang_thai = 'ACTIVE'
      AND so_luong_con_lai > 0
      AND (
          han_su_dung IS NULL
          OR han_su_dung >= TRUNC(SYSDATE)
      );

    RETURN v_ton;
END;
/


-------------------------------------------------------------------------------
-- 13. FUNCTION THÊM MỚI: tính tổng tiền phiếu nhập từ chi tiết nhập
-- Mục đích:
-- - Đối soát PHIEUNHAP.tong_tien.
-- - Dùng cho báo cáo hoặc procedure cập nhật tổng.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng. Chỉ đọc dữ liệu.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_tong_tien_phieu_nhap (
    p_ma_phieu_nhap IN NUMBER
) RETURN NUMBER
AS
    v_total NUMBER(18,2);
BEGIN
    SELECT NVL(SUM(so_luong_nhap * don_gia_nhap), 0)
    INTO v_total
    FROM CHITIETPHIEUNHAP
    WHERE ma_phieu_nhap = p_ma_phieu_nhap;

    RETURN v_total;
END;
/


-------------------------------------------------------------------------------
-- 14. FUNCTION THÊM MỚI: tính tổng giá trị phiếu xuất từ chi tiết xuất
-- Mục đích:
-- - Đối soát PHIEUXUAT.tong_gia_tri_xuat.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng. Chỉ đọc dữ liệu.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_tong_gia_tri_phieu_xuat (
    p_ma_phieu_xuat IN NUMBER
) RETURN NUMBER
AS
    v_total NUMBER(18,2);
BEGIN
    SELECT NVL(SUM(so_luong_xuat * don_gia_xuat), 0)
    INTO v_total
    FROM CHITIETPHIEUXUAT
    WHERE ma_phieu_xuat = p_ma_phieu_xuat;

    RETURN v_total;
END;
/


-------------------------------------------------------------------------------
-- 15. FUNCTION THÊM MỚI: tính tổng thanh toán hóa đơn
-- Mục đích:
-- - Đối soát HOADON.tong_thanh_toan.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng. Chỉ đọc dữ liệu.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_tong_thanh_toan_hoa_don (
    p_ma_hoa_don IN NUMBER
) RETURN NUMBER
AS
    v_total NUMBER(18,2);
BEGIN
    SELECT NVL(SUM(thanh_tien_dong), 0)
    INTO v_total
    FROM CHITIETHOADON
    WHERE ma_hoa_don = p_ma_hoa_don;

    RETURN v_total;
END;
/


-------------------------------------------------------------------------------
-- 16. FUNCTION THÊM MỚI: kiểm tra nguyên liệu dưới mức tồn tối thiểu
-- Mục đích:
-- - Trả 1 nếu tồn kho < mức tồn tối thiểu.
-- - Trả 0 nếu bình thường hoặc chưa có dòng TONKHO.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng. Có thể dùng cho màn cảnh báo tồn thấp.
-------------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_duoi_muc_ton_toi_thieu (
    p_ma_kho IN NUMBER,
    p_ma_nguyen_lieu IN NUMBER
) RETURN NUMBER
AS
    v_so_luong_ton NUMBER(18,3);
    v_muc_toi_thieu NUMBER(18,3);
BEGIN
    SELECT tk.so_luong_ton, nl.muc_ton_toi_thieu
    INTO v_so_luong_ton, v_muc_toi_thieu
    FROM TONKHO tk
    JOIN NGUYENLIEU nl
        ON nl.ma_nguyen_lieu = tk.ma_nguyen_lieu
    WHERE tk.ma_kho = p_ma_kho
      AND tk.ma_nguyen_lieu = p_ma_nguyen_lieu;

    IF v_so_luong_ton < v_muc_toi_thieu THEN
        RETURN 1;
    END IF;

    RETURN 0;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;
/


-------------------------------------------------------------------------------
-- 17. PROCEDURE ĐÃ CÓ: đồng bộ TONKHO từ LOHANG_NGUYENLIEU
-- Mục đích:
-- - Dùng khi cần bảo trì/đối soát.
-- - Không chạy tự động trong nghiệp vụ nhập/xuất.
--
-- Ảnh hưởng backend:
-- - Có COMMIT nên không nên gọi giữa transaction nghiệp vụ backend.
-- - Nếu gọi, TONKHO sẽ bị ghi lại theo tổng lô ACTIVE còn hạn.
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_dong_bo_tonkho_tu_lo (
    p_ma_kho IN NUMBER DEFAULT NULL
)
AS
BEGIN
    MERGE INTO TONKHO tk
    USING (
        WITH pairs AS (
            SELECT ma_kho, ma_nguyen_lieu
            FROM TONKHO
            WHERE p_ma_kho IS NULL OR ma_kho = p_ma_kho

            UNION

            SELECT ma_kho, ma_nguyen_lieu
            FROM LOHANG_NGUYENLIEU
            WHERE p_ma_kho IS NULL OR ma_kho = p_ma_kho
        )
        SELECT
            p.ma_kho,
            p.ma_nguyen_lieu,
            NVL((
                SELECT SUM(lh.so_luong_con_lai)
                FROM LOHANG_NGUYENLIEU lh
                WHERE lh.ma_kho = p.ma_kho
                  AND lh.ma_nguyen_lieu = p.ma_nguyen_lieu
                  AND lh.trang_thai = 'ACTIVE'
                  AND lh.so_luong_con_lai > 0
                  AND (
                      lh.han_su_dung IS NULL
                      OR lh.han_su_dung >= TRUNC(SYSDATE)
                  )
            ), 0) AS so_luong_tu_lo
        FROM pairs p
    ) src
    ON (
        tk.ma_kho = src.ma_kho
        AND tk.ma_nguyen_lieu = src.ma_nguyen_lieu
    )
    WHEN MATCHED THEN
        UPDATE SET
            tk.so_luong_ton = src.so_luong_tu_lo,
            tk.lan_cap_nhat_cuoi = CURRENT_TIMESTAMP
    WHEN NOT MATCHED THEN
        INSERT (
            ma_kho,
            ma_nguyen_lieu,
            so_luong_ton,
            lan_cap_nhat_cuoi
        )
        VALUES (
            src.ma_kho,
            src.ma_nguyen_lieu,
            src.so_luong_tu_lo,
            CURRENT_TIMESTAMP
        );

    COMMIT;
END;
/


-------------------------------------------------------------------------------
-- 18. PROCEDURE THÊM MỚI: cập nhật tổng tiền phiếu nhập
-- Mục đích:
-- - Dùng để đối soát/cập nhật lại PHIEUNHAP.tong_tien từ chi tiết.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng nếu chạy thủ công/bảo trì.
-- - Có COMMIT nên không gọi giữa transaction backend.
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_cap_nhat_tong_phieu_nhap (
    p_ma_phieu_nhap IN NUMBER DEFAULT NULL
)
AS
BEGIN
    UPDATE PHIEUNHAP pn
    SET pn.tong_tien = fn_tong_tien_phieu_nhap(pn.ma_phieu_nhap)
    WHERE p_ma_phieu_nhap IS NULL
       OR pn.ma_phieu_nhap = p_ma_phieu_nhap;

    COMMIT;
END;
/


-------------------------------------------------------------------------------
-- 19. PROCEDURE THÊM MỚI: cập nhật tổng giá trị phiếu xuất
-- Mục đích:
-- - Dùng để đối soát/cập nhật lại PHIEUXUAT.tong_gia_tri_xuat.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng nếu chạy thủ công/bảo trì.
-- - Có COMMIT nên không gọi giữa transaction backend.
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_cap_nhat_tong_phieu_xuat (
    p_ma_phieu_xuat IN NUMBER DEFAULT NULL
)
AS
BEGIN
    UPDATE PHIEUXUAT px
    SET px.tong_gia_tri_xuat = fn_tong_gia_tri_phieu_xuat(px.ma_phieu_xuat)
    WHERE p_ma_phieu_xuat IS NULL
       OR px.ma_phieu_xuat = p_ma_phieu_xuat;

    COMMIT;
END;
/


-------------------------------------------------------------------------------
-- 20. PROCEDURE THÊM MỚI: cập nhật tổng thanh toán hóa đơn
-- Mục đích:
-- - Dùng để đối soát/cập nhật HOADON.tong_thanh_toan.
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng nếu chạy thủ công/bảo trì.
-- - Có COMMIT nên không gọi giữa transaction backend.
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_cap_nhat_tong_hoa_don (
    p_ma_hoa_don IN NUMBER DEFAULT NULL
)
AS
BEGIN
    UPDATE HOADON hd
    SET hd.tong_thanh_toan = fn_tong_thanh_toan_hoa_don(hd.ma_hoa_don)
    WHERE p_ma_hoa_don IS NULL
       OR hd.ma_hoa_don = p_ma_hoa_don;

    COMMIT;
END;
/


-------------------------------------------------------------------------------
-- 21. PROCEDURE THÊM MỚI: báo cáo tồn thấp bằng SYS_REFCURSOR
-- Mục đích:
-- - Trả danh sách nguyên liệu có so_luong_ton < muc_ton_toi_thieu.
-- - Có thể dùng cho SQL Developer, backend hoặc demo.
--
-- Cách test SQL Developer:
-- VAR rc REFCURSOR;
-- EXEC prc_bao_cao_ton_thap(NULL, :rc);
-- PRINT rc;
--
-- Ảnh hưởng backend:
-- - Không ảnh hưởng. Chỉ đọc dữ liệu.
-------------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE prc_bao_cao_ton_thap (
    p_ma_kho IN NUMBER DEFAULT NULL,
    p_result OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_result FOR
        SELECT
            k.ma_kho,
            k.ten_kho,
            nl.ma_nguyen_lieu,
            nl.ten_nguyen_lieu,
            dvt.ky_hieu AS don_vi_tinh,
            tk.so_luong_ton,
            nl.muc_ton_toi_thieu,
            tk.lan_cap_nhat_cuoi
        FROM TONKHO tk
        JOIN KHO k
            ON k.ma_kho = tk.ma_kho
        JOIN NGUYENLIEU nl
            ON nl.ma_nguyen_lieu = tk.ma_nguyen_lieu
        JOIN DONVITINH dvt
            ON dvt.ma_don_vi_tinh = nl.ma_don_vi_tinh
        WHERE tk.so_luong_ton < nl.muc_ton_toi_thieu
          AND (p_ma_kho IS NULL OR tk.ma_kho = p_ma_kho)
        ORDER BY k.ten_kho, nl.ten_nguyen_lieu;
END;
/